package uz.zero_one.chat

enum class ChatType {
    PRIVATE, GROUP
}

enum class UserStatus {
    ONLINE,
    OFFLINE
}

enum class MemberRole {
    OWNER, MEMBER,ADMIN
}

enum class ErrorCode(val code: Int){
    TELEGRAM_ID_NOT_FOUND_EXCEPTION(100),
    INVALID_TELEGRAM_DATA_EXCEPTION(101),
    USER_NOT_FOUND_EXCEPTION(102),
    CHAT_NOT_FOUND_EXCEPTION(103),
    CHAT_ACCESS_DENIED(104),
    CHAT_MEMBER_NOT_FOUND(105),
    USERNAME_NOT_FOUND_EXCEPTION(106),
    MESSAGE_NOT_FOUND_EXCEPTION(107),
    MESSAGE_ACCESS_DENIED_EXCEPTION(108),
    MESSAGE_CHAT_MISMATCH_EXCEPTION(109)
}

enum class MessageType {
    TEXT,
    IMAGE,
    VIDEO,
    FILE,
    AUDIO,
    LOCATION,
    POLL,
    DOCUMENT,
    OTHER
}
